backend:
  name: git-gateway
  branch: main

# Uncomment below to enable drafts https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
